=== TLoebner/openims_core_ims/ser_ims/branches/02_persistency/doc/stylesheets/dbschema/dtd/dbschema.dtd
<!ELEMENT database (name, description?, table*)>
<!ATTLIST database
    id ID #IMPLIED
>

<!ELEMENT name (#PCDATA) >

<!ELEMENT description (#PCDATA) >

<!ELEMENT table (name, description?, version?, column+, index*, row*) >
<!ATTLIST table
    id ID #IMPLIED
>

<!ELEMENT version (#PCDATA) >

<!ELEMENT column (name, description?, type, size?, default?, null?) >
<!ATTLIST column
    id ID #IMPLIED
>

<!ELEMENT index (name?, unique?, colref+) >
<!ATTLIST index
    id ID #IMPLIED
>

<!ELEMENT type (#PCDATA) >
<!ATTLIST type
    auto_increment (yes|no) #IMPLIED
>

<!ELEMENT size (#PCDATA) >

<!ELEMENT default (#PCDATA) >

<!ELEMENT null EMPTY >

<!ELEMENT unique EMPTY >

<!ELEMENT colref EMPTY>
<!ATTLIST colref
    linkend IDREF #REQUIRED
>

<!ELEMENT row-identificator (colref+) >

<!ELEMENT row (value*) >
<!ATTLIST row
    vendor-controlled (0|1) #IMPLIED
>

<!ELEMENT value (#PCDATA | null)* >
<!ATTLIST value
    col IDREF #REQUIRED
>

=== TLoebner/openims_core_ims/ser_ims/branches/02_persistency/db/schema/silo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//iptel.org//DTD DBSchema V1.0//EN"
  "http://iptel.org/dbschema/dtd/1.0/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table xmlns:my="http://iptel.org/dbschema/mysql"
    xmlns:pg="http://iptel.org/dbschema/postgres"
    xmlns:dt="http://iptel.org/dbschema/dbtext">
    <name>silo</name>
    <version>4</version>

    <column id="silo.mid">
	<name>mid</name>
	<type>int</type>
	<my:type>INT AUTO_INCREMENT</my:type>
	<pg:type>SERIAL</pg:type>
	<dt:type>int,auto</dt:type>
    </column>

    <column>
	<name>from_hdr</name>
	<type>string</type>
	<size>255</size>
    </column>

    <column>
	<name>to_hdr</name>
	<type>string</type>
	<size>255</size>
    </column>

    <column>
	<name>ruri</name>
	<type>string</type>
	<size>&uri_len;</size>
    </column>

    <column>
	<name>uid</name>
	<type>string</type>
	<size>&id_len;</size>
    </column>

    <column>
	<name>inc_time</name>
	<type>datetime</type>
	<default>1970-01-01 00:00:00</default>
    </column>

    <column>
	<name>exp_time</name>
	<type>datetime</type>
	<default>1970-01-01 00:00:00</default>
    </column>

    <column>
	<name>ctype</name>
	<type>string</type>
	<default>text/plain</default>
	<size>128</size>
    </column>

    <column>
	<name>body</name>
	<type>binary</type>
	<default></default>
    </column>

    <index>
	<unique/>
	<name>silo_idx1</name>
	<colref linkend="silo.mid"/>
    </index>
</table>

=== TLoebner/openims_core_ims/ser_ims/branches/02_persistency/db/schema/speed_dial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//iptel.org//DTD DBSchema V1.0//EN"
  "http://iptel.org/dbschema/dtd/1.0/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table xmlns:my="http://iptel.org/dbschema/mysql"
    xmlns:pg="http://iptel.org/dbschema/postgres"
    xmlns:dt="http://iptel.org/dbschema/dbtext">
    <name>speed_dial</name>
    <version>2</version>

    <column id="sd.id">
	<name>id</name>
	<type>int</type>
	<my:type>INT AUTO_INCREMENT</my:type>
	<pg:type>SERIAL</pg:type>
	<dt:type>int,auto</dt:type>
    </column>

    <column id="sd.uid">
	<name>uid</name>
	<type>string</type>
	<size>&id_len;</size>
    </column>

    <column id="sd.dial_username">
	<name>dial_username</name>
	<type>string</type>
	<size>&user_len;</size>
    </column>

    <column id="sd.dial_did">
	<name>dial_did</name>
	<type>string</type>
	<size>&id_len;</size>
    </column>

    <column>
	<name>new_uri</name>
	<type>string</type>
	<size>&uri_len;</size>
    </column>

    <index>
	<name>speeddial_idx1</name>
	<unique/>
	<colref linkend="sd.uid"/>
	<colref linkend="sd.dial_did"/>
	<colref linkend="sd.dial_username"/>
    </index>

    <index>
	<unique/>
	<name>speeddial_id</name>
	<colref linkend="sd.id"/>
    </index>

    <index>
	<name>speeddial_uid</name>
	<colref linkend="sd.uid"/>
    </index>
</table>

=== TLoebner/openims_core_ims/ser_ims/branches/02_persistency/db/schema/gw_grp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table PUBLIC "-//iptel.org//DTD DBSchema V1.0//EN"
  "http://iptel.org/dbschema/dtd/1.0/dbschema.dtd" [

<!ENTITY % entities SYSTEM "entities.xml">
%entities;

]>

<table xmlns:my="http://iptel.org/dbschema/mysql"
    xmlns:pg="http://iptel.org/dbschema/postgres"
    xmlns:dt="http://iptel.org/dbschema/dbtext">
    <name>gw_grp</name>
    <version>2</version>

    <column id="gw_grp.id">
	<name>grp_id</name>
	<type>int</type>
	<my:type>INT AUTO_INCREMENT</my:type>
	<pg:type>SERIAL</pg:type>
	<dt:type>int,auto</dt:type>
    </column>

    <column>
	<name>grp_name</name>
	<type>string</type>
	<size>64</size>
    </column>

    <index>
	<name>gwgrp_idx</name>
	<unique/>
	<colref linkend="gw_grp.id"/>
    </index>
</table>
